version: '3.8'
services:

  # Access at http://localhost:8180/
  nginx:
    depends_on:
      - demo-app
    image: nginx:latest
    networks:
      - default
    ports:
      - "8180:8180"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d/default.conf

  demo-app:
    image: 'demo/app:latest'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Client__ApiUrl: '/'
      OpenTelemetry__Exporters__Otlp__Seq__Endpoint: 'http://seq:5341/ingest/otlp/v1/logs'
      OpenTelemetry__Exporters__Otlp_Jaeger__Endpoint: 'http://jaeger:4317/'
      PathBase: '/'
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
