version: '3.8'
services:

  demo-app:
    image: 'demo/app:latest'
    environment:
      ASPNETCORE_ENVIRONMENT: Compose
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OpenTelemetry__Logs__Exporters__0: Otlp
      OpenTelemetry__Traces__Exporters__0: Otlp
      OpenTelemetry__Debug: true
      OpenTelemetry__OtlpDebug: true
    ports:
      - "8080:8080"
    networks:
      - default

  jaeger:
    # UI: http://localhost:16686/
    image: 'jaegertracing/all-in-one:1.50'
    networks:
      - default
    ports:
      - '4317:4317' # OTLP
      - '16686:16686' # UI
    restart: unless-stopped

  seq:
    # UI: http://localhost:8341/
    # Login: admin / seqdev123
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      # Generate hash via: echo 'seqdev123' | podman run --rm -i datalust/seq:latest config hash
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: 'QE1HKtHw6CD5cDyxTDqaNDWWZkqUaq4EbOj9nyFgScHe/fT3SJPB7DmjlZVpVLXk9amcmZig4XS/F/htkCloum2Q3cjWXo1/bzoaJUV6r2m6'
    networks:
      - default
    ports:
      - "8341:80"
      - "5341:5341"
    restart: unless-stopped
    volumes:
      - seq-data:/data

  otel-collector:
    depends_on:
      - jaeger
      - seq
    image: otel/opentelemetry-collector
    networks:
      - default
    ports:
      - "24317:4317"
      - "24318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml

  # Access at http://localhost:8180/
  nginx:
    depends_on:
      - otel-collector
      - demo-app
    image: nginx:latest
    networks:
      - default
    ports:
      - "8180:8180"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d/default.conf

  seq:
    # UI: http://localhost:8341/
    # Login: admin / seqdev123
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      # Generate hash via: echo 'seqdev123' | podman run --rm -i datalust/seq:latest config hash
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: 'QE1HKtHw6CD5cDyxTDqaNDWWZkqUaq4EbOj9nyFgScHe/fT3SJPB7DmjlZVpVLXk9amcmZig4XS/F/htkCloum2Q3cjWXo1/bzoaJUV6r2m6'
    networks:
      - default
    ports:
      - "8341:80"
      - "5341:5341"
    restart: unless-stopped
    volumes:
      - seq-data:/data

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default

volumes: 
  seq-data:
    driver: local
