
FROM nginx:1.26.2 AS nginx
RUN apt update ; apt install -y curl gnupg ca-certificates debian-archive-keyring
RUN curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian bookworm nginx" | tee /etc/apt/sources.list.d/nginx.list
RUN apt update
RUN apt install -y nginx-module-otel
RUN echo "load_module modules/ngx_otel_module.so;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf
