receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  otlp/1:
    protocols:
      http:
        endpoint: http://seq:5341/ingest/otlp/v1/logs
  otlp/2:
    protocols:
      grpc:
        endpoint: http://jaeger:4317/
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/2]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp/1]
