version: '3.8'
services:

  seq:
    # UI: http://localhost:8341/
    # Login: admin / seqdev123
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      # Generate hash via: echo 'seqdev123' | podman run --rm -i datalust/seq:latest config hash
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: 'QE1HKtHw6CD5cDyxTDqaNDWWZkqUaq4EbOj9nyFgScHe/fT3SJPB7DmjlZVpVLXk9amcmZig4XS/F/htkCloum2Q3cjWXo1/bzoaJUV6r2m6'
    networks:
      - default
    ports:
      - "8341:80"
      - "5341:5341"
    restart: unless-stopped
    volumes:
      - seq-data:/data

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default

volumes: 
  seq-data:
    driver: local
