import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <Script strategy="beforeInteractive" id="windowAppConfig">
        {`window.appConfig = {
            "apiUrl": "` + process.env.NEXT_PUBLIC_API_URL + `",
            "environment": "` + process.env.NEXT_PUBLIC_ENVIRONMENT + `",
            "pathBase": "` + process.env.NEXT_PUBLIC_PATH_BASE + `",
            "tracePropagateCorsUrls": "` + process.env.NEXT_PUBLIC_TRACE_PROPAGATE_CORS_URLS + `",
            "version": "` + process.env.NEXT_PUBLIC_VERSION + `",
        }`}
        </Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
