@startuml

left to right direction
skinparam { 
    ComponentBackgroundColor white
    ComponentBorderThickness 2
    'ComponentStyle rectangle
    CloudBorderThickness 2
    DatabaseBorderThickness 2
    Handwritten true
    QueueBorderThickness 2
    'RectangleBackgroundColor white
    RectangleBorderThickness 2
}

'skinparam {
'    ComponentBorderColor #0e39fb
'    ComponentFontColor #0e39fb
'    RectangleBorderColor #0e39fb
'    RectangleFontColor #0e39fb
'    ArrowColor #0e39fb
'}

component Demo.WebApp {
    rectangle webapp_exporter as "OTLP Exporter" #ffffff
}
component Demo.Service {
    rectangle service_exporter as "OTLP Exporter" #ffffff
}
component Demo.Worker {
    rectangle worker_exporter as "OTLP Exporter" #ffffff
}

rectangle otel_collector as "OpenTelemetry\nCollector"

rectangle Elasticsearch [
    Elasticsearch
    (logs)
]
rectangle Kibana
rectangle Jaeger [
    Jaeger
    (traces)
]

cloud azure_monitor [
    Azure Monitor
    (traces, logs)
]

webapp_exporter -- otel_collector
service_exporter -- otel_collector
worker_exporter -- otel_collector

otel_collector -- Jaeger
otel_collector -- Elasticsearch
Elasticsearch -- Kibana

'otel_collector -- Prometheus
otel_collector -- azure_monitor

'cloud nr_otlp [
'    NewRelic
'    (traces, logs)
']
'webapp_exporter -- nr_otlp
'service_exporter -- nr_otlp
'worker_exporter -- nr_otlp

@endml
