version: '3.8'
services:

  aspire-dashboard:
    # UI: To get the security key view the logs, e.g.
    #   podman logs blazor-2024_aspire-dashboard_1
    image: 'mcr.microsoft.com/dotnet/aspire-dashboard:latest'
    networks:
      - default
    ports:
      - '4317:18889' # OTLP
      - '18888:18888' # UI
    restart: unless-stopped
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
